experiment_name: Features_resnet101_rumc
model:
    model_name: "resnet101"
    num_classes: 4
    freeze_weights: False
    num_frozen_layers: 0
    dropout: 0.2
    embedding_bool: True
    pool_algorithm: "attention"
    hidden_space_len: 128

dataset:
    magnification: "10"
    mean: [0.485, 0.456, 0.406]
    stddev: [0.229, 0.224, 0.225]

dataloader:
    batch_size_bag: 1
    batch_size: 512
    num_workers: 6

data_augmentation:
    boolean: False
    featuresdir: Features_resnet101_rumc
    prob: 0.5

