# Docker compose to run the docker image lluisb3/mask3d (non-root image)#
# Create image running docker-build-script.sh to create user with same ID as hosr user #
# IMPORTANT to create directories in volumes on the host machine with user ownership before running #
# Variables as "${TAG} , ${WSI_NAME}" and "${SIGMA}" are defined in the .env file 

services:
  hlung:
    image: lluisb3/hlung:${TAG} 
    container_name: hlung
    volumes:
      - /home/elias/tbSectra/ai/data/tcga:/home/user/appHistolung/data/tcga
      - /home/elias/tbSectra/ai/data/outputs:/home/user/appHistolung/data/outputs
      - /home/elias/tbSectra/ai/histo_lung/.env:/home/user/appHistolung/.env:ro
    # Entrypoint to run the heatmaps script with the WSI_NAME and SIGMA as arguments in the .env file
    entrypoint: ["python3", "-u", "-m", "heatmaps.heatmaps", "--wsi_name", "${WSI_NAME}", "--sigma", "${SIGMA}"]
