experiment_name: MIL_00025_210_256
model:
    model_name: "resnet34"
    num_classes: 4
    freeze_weights: False
    num_frozen_layers: 0
    dropout: 0.2
    embedding_bool: True
    pool_algorithm: "attention"
    hidden_space_len: 128

dataset:
    magnification: "10"
    mean: [0.485, 0.456, 0.406]
    stddev: [0.229, 0.224, 0.225]

dataloader:
    batch_size_bag: 1
    batch_size: 256
    num_workers: 6

data_augmentation:
    prob: 0.5

training:
    num_keys: 32768
    moco_dim: 128
    moco_m: 0.999
    temperature: 0.07
    epochs: 40
    early_stop: 10
    criterion: BCEWithLogitsLoss
    optimizer: "Adam"
    optimizer_args:
        lr: 0.00025
        betas:
        - 0.9
        - 0.999
        eps: 1.0e-08
        weight_decay: 1.0e-4
        amsgrad: True
    # optimizer_args:
    #     lr: 0.01
    #     momentum: 0.9
    #     weight_decay: 1e-4
    lr_scheduler: 'MultiStepLR'
    lr_scheduler_args:
        milestones: [2, 10, 20, 30]
        gamma: 0.5
    best_metric: 'accuracy'
    resume_training: False

wandb:
  enable: True
  project: "histo_lung"
  username: "lluisb3"
  group: "MIL"
