experiment_name: f_MIL_convnext_weights_cosine_less
model:
    model_name: "convnext"
    num_classes: 4
    freeze_weights: False
    num_frozen_layers: 0
    dropout: 0.2
    embedding_bool: True
    pool_algorithm: "attention"
    hidden_space_len: 128

dataset:
    magnification: "10"
    mean: [0.485, 0.456, 0.406]
    stddev: [0.229, 0.224, 0.225]

dataloader:
    batch_size_bag: 1
    batch_size: 512
    num_workers: 6

data_augmentation:
    boolean: False
    featuresdir: Features_convnext_NoChannel
    prob: 0.5

training:
    epochs: 50
    early_stop: 20
    criterion: BCEWithLogitsLoss
    criterion_args:
        weights: [0.824, 0.477, 0.809, 0.742]
    optimizer: "Adam"
    optimizer_args:
        lr: 0.00015
        betas:
        - 0.9
        - 0.999
        eps: 1.0e-08
        weight_decay: 1.0e-4
        amsgrad: True
    # optimizer_args:
    #     lr: 0.01
    #     momentum: 0.9
    #     weight_decay: 1e-4
    lr_scheduler: 'CosineAnnealingLR'
    lr_scheduler_args:
        T_max: 3
        eta_min: 0.00005
    resume_training: False

wandb:
  enable: True
  project: "histo_lung"
  username: "lluisb3"
  group: "MIL_feat"

