experiment_name: MoCo_try
model:
    model_name: 'resnet50'
    num_classes: 4
    freeze_weights: False
    num_frozen_layers: 0
    dropout: 0.2
    embedding_bool: True

dataset:
    magnification: 10
    mean: [0.485, 0.456, 0.406]
    stddev: [0.229, 0.224, 0.225]
    use_masks: False
    resize: 224

dataloader:
    batch_size_bag: 16
    batch_size: 256
    num_workers: 4

data_aug:
    prob: 0.5

training:
    num_keys: 32768
    moco_dim: 128
    moco_m: 0.999
    temperature: 0.07
    criterion: 'CrossEntropyLoss'
    criterion_args:
        weight: [0.46615505706414795, 0.607831562377017,0.9260133805588351]
    optimizer: 'SGD'
    optimizer_args:
        lr: 0.01
        momentum: 0.9
    lr_scheduler: 'MultiStepLR'
    lr_scheduler_args:
        milestones: [10,25,30,45]
        gamma: 0.1
    epochs: 20
    early_stop: 10
    best_metric: 'accuracy'
    resume_training: False
