data_augmentation:
  boolean: false
  featuresdir: Features_resnet34_v2_NoChannel
  prob: 0.5
dataloader:
  batch_size: 512
  batch_size_bag: 1
  num_workers: 1
dataset:
  magnification: '10'
  mean:
  - 0.485
  - 0.456
  - 0.406
  stddev:
  - 0.229
  - 0.224
  - 0.225
experiment_name: f_MIL_res34v2_v2_rumc_best_cosine_v3_tryNew
model:
  dropout: 0.2
  embedding_bool: true
  freeze_weights: false
  hidden_space_len: 128
  model_name: resnet34
  num_classes: 4
  num_frozen_layers: 0
  pool_algorithm: attention
training:
  criterion: BCEWithLogitsLoss
  criterion_args:
    weights:
    - 0.824
    - 0.477
    - 0.809
    - 0.742
  early_stop: 15
  epochs: 40
  lr_scheduler: CosineAnnealingLR
  lr_scheduler_args:
    T_max: 10
    eta_min: 3.0e-05
  optimizer: Adam
  optimizer_args:
    amsgrad: true
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 0.0003
    momentum: 0.9
    weight_decay: 0.0001
  resume_training: false
wandb:
  enable: true
  group: MIL_best
  project: histo_lung
  username: lluisb3
