experiment_name: MIL_0001_convnext_focal_feat_sche01_NoAChannel
model:
    model_name: "convnext"
    num_classes: 4
    freeze_weights: False
    num_frozen_layers: 0
    dropout: 0.2
    embedding_bool: True
    pool_algorithm: "attention"
    hidden_space_len: 128

dataset:
    magnification: "10"
    mean: [0.485, 0.456, 0.406]
    stddev: [0.229, 0.224, 0.225]

dataloader:
    batch_size_bag: 1
    batch_size: 512
    num_workers: 6

data_augmentation:
    boolean: False
    featuresdir: Features_convnext_NoChannel
    prob: 0.5

training:
    num_keys: 32768
    moco_dim: 128
    moco_m: 0.999
    temperature: 0.07
    epochs: 50
    early_stop: 20
    criterion: focal
    criterion_args:
        weights: None
    optimizer: "Adam"
    optimizer_args:
        lr: 0.001
        betas:
        - 0.9
        - 0.999
        eps: 1.0e-08
        weight_decay: 1.0e-4
        amsgrad: True
    # optimizer_args:
    #     lr: 0.01
    #     momentum: 0.9
    #     weight_decay: 1e-4
    lr_scheduler: 'MultiStepLR'
    lr_scheduler_args:
        milestones: [2, 5, 12, 30]
        gamma: 0.5
    resume_training: False

wandb:
  enable: True
  project: "histo_lung"
  username: "lluisb3"
  group: "MIL"
