data_aug:
  prob: 0.5
dataloader:
  batch_size: 256
  batch_size_bag: 16
  num_workers: 4
dataset:
  magnification: 10
  mean:
  - 0.485
  - 0.456
  - 0.406
  resize: 224
  stddev:
  - 0.229
  - 0.224
  - 0.225
  use_masks: false
experiment_name: MoCo_try
model:
  dropout: 0.2
  embedding_bool: true
  freeze_weights: false
  model_name: resnet50
  num_classes: 4
  num_frozen_layers: 0
training:
  best_metric: accuracy
  criterion: CrossEntropyLoss
  criterion_args:
    weight:
    - 0.46615505706414795
    - 0.607831562377017
    - 0.9260133805588351
  early_stop: 10
  epochs: 20
  lr_scheduler: MultiStepLR
  lr_scheduler_args:
    gamma: 0.1
    milestones:
    - 10
    - 25
    - 30
    - 45
  moco_dim: 128
  moco_m: 0.999
  num_keys: 32768
  optimizer: SGD
  optimizer_args:
    lr: 0.01
    momentum: 0.9
  resume_training: false
  temperature: 0.07
